server:
  port: ${PORT:8080}

spring:
  profiles:
    active:
      - dev
  datasource:
    url: jdbc:mysql://${DB_AIM_IP}/db_users
    username: ${DB_AIM_USER_USERNAME}
    password: ${DB_AIM_USER_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  data:
    rest:
      base-path: /api
