server:
  port: ${PORT:8080}

spring:
  profiles:
    active:
      - dev
  datasource:
    url: jdbc:mysql://localhost:3306/users_db
    username: root
    password: sprz€d@m0pla
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  data:
    rest:
      base-path: /api
