server:
  port: ${PORT:8080}

spring:
  profiles:
    active:
      - dev
  datasource:
    url: jdbc:h2:file:./users
    driverClassName: org.h2.Driver
    username: ${USER_DB_USERNAME_AIM}
    password: ${USER_DB_PASSWORD_AIM}
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  data:
    rest:
      base-path: /api
