server:
  port: ${PORT:8080}

spring:
  profiles:
    active:
      - dev
  datasource:
    url: jdbc:h2:mem:usersdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
