version: 2.1

orbs:
  heroku: circleci/heroku@1.2.5

workflows:
  Check, Build and Test:
    jobs:
      - Static Analysis
      - Build
      - Test:
          requires:
            - Build

  Deploy Backend:
    jobs:
      - Trigger Deploy Backend:
          type: approval
          filters:
            branches:
              only: /.*/

      - Deploy Backend to Heroku:
          requires:
            - Trigger Deploy Backend

  Deploy Frontend:
    jobs:
      - Trigger Deploy Frontend:
          type: approval
          filters:
            branches:
              only: /.*/

      - Deploy Frontend to Heroku:
          requires:
            - Trigger Deploy Frontend

jobs:
  Static Analysis:
    docker:
      - image: circleci/openjdk:11-jdk

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - run: gradle ktlintCheck
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle.kts" }}

  Build:
    docker:
      - image: circleci/openjdk:11-jdk

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle.kts" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Load dependencies
          command: gradle dependencies

      - save_cache:
          name: Execute build script
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle.kts" }}

      - run:
          name: Build Jar
          command: gradle bootJar

  Test:
    docker:
      - image: circleci/openjdk:11-jdk

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle.kts" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Run tests
          command: gradle test

  Deploy Backend to Heroku:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git

  Deploy Frontend to Heroku:
    docker:
      - image: circleci/openjdk:11-jdk

    working_directory: ~/frontend
    steps:
      - run: git clone https://github.com/aimachine-project/aimachine-frontend.git
      - run: ls
